language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: tizmJTTA1H1oKXfqYTZgBVaU/leiqzrCIaHyQr3lsuobikytCk25HgbJgDR0pbC3Dv99Euf+QISC/zhQzKHCTfz0JwU4MMtYV6VJzmldBqbhwcYn2AeBwINapdf4TLGDRPcxqc+0VWQ64cRaQIHmX7ZwG8OUZjN/o8j4dw1ULuK8KEl+hpAsu8RuNk1WrNFCJvXzjMX61gmpeEqdb7rJ43H7gGmH+K8mgRnTxevqCSZ2GjOspSRLo+dTT0xTVGcUB8TDziUwUlfcHOAJGiLamoZYYBGSHUHoTmci59V+KPGAxI2G2RRKpwdZJmBVchLk5wBBuYBPCcSXCFaZqWMiwIUzarJTLBaWhxyFObovtVfJ4D1msR+LG9JMtg4Uf0Y5LYN81/YomOpPEnsnecm3itK5wsjwtEDU54ix7gO+uvjbxUHSpKxakuuP4JhtAfIznU65hLlWKLsGPy3zTdRLI7n9dBMYYkmBoCSvsu2va5eGo+VTWXvd6bIkiO84q/0rXDjJB7MCOLHeLujeEGsNaT+EFT696HFJRWHSInPzLy5QNVUU8gvg814A5cDnPqGLjFnG8IARioq+z35KjeL4q0qE12AJ8jccrYTZD8J+NEoW+LKIX4sVAX9x/WAoxzmSDwM6PsdPwF8aI1mc4S7jexku7oih2c82aLM5nrFtoiQ=
  - secure: vObxgTwZ1711jC49opciPUfM3jOR2axSHiWwsskilxgGAiqrViy0L5Mr4Aca9SWnTufwjVETzEe/HiH/TPxPOKca5jP23fKefezf8iDiMPN0ACqRCrXc2gVAUMZ1zRiI9ApazLcXoMN/AbeL18g3bw5++MCg7wqNJhpNLiShCMDEX1BLmLGmnnyfvyrXNaNYSVBvHn6+a35wJWq/bDvTkDm4PqtlEFLaU8Dze4L2IHdy/1V3ITqexUW+uAWqREOlGoaktKusdPehHlSLyQf0O78xZJ34JW6KcEznTlDeB/eIL9rMnHMDAFAdZMjHxbm2C3yBxkw4qmDP1hFUVYqBpOX7YnL2g7ESRJIwk1dCXprIbPO6q5b9EIffsWf9uP+4zMM4/3fQyGFg360ub++v3FpAVRqxtTVL8kBN5urDCqBTf6XBubws3Yv/b3vkUCED0rbXPBF+48VJSmFDOhBnzC9E5GxtnloACTwgnHU8is6OO/G0fo6qwijBM4Epn2fb6p23WDTHEyeiG2DHrjsr+9Yovoqcm1fZhh7frA/cjpsT+iNt6A0YJ7HE/8GNIqW1r7VgIO+Zfz0qnUMqlaO2FfpE8hFgSpnFe6uYxQqYukYatxfHYu24BUzsW2wpdyL6nffCsRuvexrTi/bGToQdqoaf28Py/89xbHIdJJ6CwPM=
