baseurl = "https://www.elearnvietnamese.com/"
languageCode = "en-us"
title = "eLearn Vietnamese"
theme = "hugo-creative-theme"
googleAnalytics = "UA-36343792-1"
disqusShortname = "elearnvietnamese"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "eLearn Vietnamese"
	description = "Vietnamese eLearning solutions built on modern web standards"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "eLearn Vietnamese"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			aside  = "Showcase"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Learn Vietnamese online <br> on any device"
		subtitle   = "eLearn Vietnamese creates engaging & interactive e-Learning content for learning Vietnamese"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "eLearn Vietnamese was created by Benjamin Waller, an educator, with the aim of giving you the best change at learning Vietnamese the right way with the right tools with the benefit of tried and tested methodologies. We develop eLearning resources with engaging, integrative and authentic content."
		buttonText  = "See our showcase"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Quality eLearning"
            description = "All our elearning is developed with a learner-centric approach with guided, logical and sequential steps to aid the learning process."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "Our eLearning solutions are made using modern web technologies so they work on any device and are kept up-to-date!"

		[[params.services.list]]
            icon = "fa-clock-o"
            title = "Convenient"
            description = "Each activity is self-contained, situational and concise which allows you to easily fit them into your day."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "Our team is passionate about Vietnamese so each and ever learning integration is carefuly crafted and considered."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "eLearn Vietnamese Showcase"

		[params.aside.button]
			text = ""
			link = ""

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start learning Vietnamese or want us to build you customised eLearning content for learning Vietnamese? That's great! Send us an email and we will get back to you as soon as possible!"
		phone = ""
		email = "info@elearnvietnamese.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
